server:
  port: 8284

spring:
    application:
      name: async-task
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
#    redis:
#      database: 0
#      hostName: 120.78.60.206
#      port: 6379
#      password: 123456
#      encode: utf-8
#      pool:
#        maxIdle: 300
#        maxTotal: 600
#        timeBetweenEvictionRunsMillis: 30000
#        minEvictableIdleTimeMillis: 30000
#        testOnBorrow: true
#      key_prefix: 
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:10.10.203.172}:${MYSQL_PORT:3306}/jsis_test?useUnicode=true&characterEncoding=UTF8
        username: test
        password: Jht123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


#eureka:
#    instance:
#        statusPageUrlPath: /actuator/info  #服务信息
#        healthCheckUrlPath: /actuator/health  #服务心跳
#        #hostname: 10.10.203.105
#        hostname: 10.101.90.220  #服务注册中心ip
#
#        preferIpAddress: true  #是否使用ip注册到服务中心
#        #instance-id: 10.10.203.105:${server.port}
#        instance-id: 10.101.90.220:${server.port}  #当前服务的访问地址
#    client:
#        enabled: true
#        serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/

spring:
  profiles:
    active: dev
# java -jar log.jar --spring.profiles.active=dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

info:
  version: '@project.version@'
  
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

mybatis:
    basepackage: rh.springcloud.mycat.mapper.user.UserInfoMapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: classpath*:mapper/**/*.xml