#logging:
#  config: config/logback.xml

spring:
    profiles:
        active: pro
    application:
        name: service-center
#启动端口
server:
    port: 8751
    

endpoints:
  shutdown:
    enabled: true     #启用shutdown
    sensitive: false  #禁用密码验证


eureka:
    instance:
#        hostname: 10.10.203.105
        hostname: localhost
        preferIpAddress: true  # 使用IP注册
        lease-renewal-interval-in-seconds: 3  # 心跳间隔
        lease-expiration-duration-in-seconds: 10  # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        eureka-service-url-poll-interval-seconds: 60  # 客户端从Eureka Server集群里更新Eureka Server信息的频率
        registry-fetch-interval-seconds: 5  # 定义从注册中心获取注册服务的信息
    server:
        enable-self-preservation: false  # 关闭自我保护模式
        eviction-interval-timer-in-ms: 3000  # 设置清理间隔,单位为毫秒,默认为0
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/